name: Build

on: 
  push:

jobs:

  build_window_dll:
    name: Windows
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        cd win
        .\make_win64.bat
    - name: Prepare
      run: |
        mkdir qjs/Lib/Win64/
        copy win/build/Release/v8qjs.lib qjs/Lib/Win64/
    - uses: actions/upload-artifact@v2
      with:
        name: qjs_v8
        path: qjs/**/*
        

